return {
	-- 	{
	-- >	"zbirenbaum/copilot.lua",
	-- 		cmd = "Copilot",
	-- 		build = ":Copilot auth",
	-- 		opts = {
	-- 			suggestion = {
	-- 				enabled = true,
	-- 				auto_trigger = true,
	-- 				keymap = {
	-- 					accept = "<C-l>",
	-- 					next = "<C-j>",
	-- 					prev = "<C-k>",
	-- 					dismiss = "<C-h>",
	-- 				},
	-- 			},
	-- 			panel = {
	-- 				enabled = true,
	-- 				auto_refresh = false,
	-- 				keymap = {
	-- 					jump_prev = "[[",
	-- 					jump_next = "]]",
	-- 					accept = "<CR>",
	-- 					refresh = "gr",
	-- 					open = "<M-CR>",
	-- 				},
	-- 				layout = {
	-- 					position = "bottom",
	-- 					ratio = 0.4,
	-- 				},
	-- 			},
	-- 			filetypes = {
	-- 				markdown = true,
	-- 				help = true,
	-- 			},
	-- 		},
	-- 	},
}
