# PATH configurations
fish_add_path /usr/local/share/dotnet
fish_add_path $HOME/.dotnet/tools
fish_add_path /opt/homebrew/opt/ruby/bin
fish_add_path /Library/TeX/texbin
fish_add_path $HOME/.modular/bin
fish_add_path $HOME/.cabal/bin
fish_add_path $HOME/.ghcup/bin
fish_add_path /Applications/Postgres.app/Contents/Versions/latest/bin
fish_add_path /usr/local/go/bin
fish_add_path /Users/danielbolivar/.avm/bin
fish_add_path /Users/danielbolivar/.local/share/solana/install/active_release/bin
fish_add_path $HOME/.cargo/bin
fish_add_path /usr/local/sbin
fish_add_path /usr/local/bin
fish_add_path $BUN_INSTALL/bin
fish_add_path $PNPM_HOME
fish_add_path $HOME/.claude/local
fish_add_path /opt/homebrew/bin
fish_add_path $HOME/.npm-global/bin
fish_add_path $HOME/.local/bin
