# Configuration for Alacritty
[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 1.0
startup_mode = "Windowed"
title = "Terminal"
dynamic_title = true
option_as_alt = "Both"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 16.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors.primary]
foreground = "#dfdef2"
background = "#181723"

[colors.normal]
red = '#eb6f92'
green = '#9ccfd8'

[colors.bright]
red = '#eb6f92'
green = '#9ccfd8'

[cursor]
style = { shape = "Block", blinking = "Off" }
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0001\u0025" # local tmux prefix + %

[[keyboard.bindings]]
key = "LBracket"
mods = "Command"
chars = "\u0001\u004f" # local tmux prefix + O (rotate clockwise)

[[keyboard.bindings]]
key = "RBracket"
mods = "Command"
chars = "\u0001\u006f" # local tmux prefix + o (rotate counter-clockwise)

[[keyboard.bindings]]
key = "D"
mods = "Command|Shift"
chars = "\u0002\u0025" # remote tmux prefix + %

[[keyboard.bindings]]
key = "LBracket"
mods = "Command|Shift"
chars = "\u0002\u004f" # remote tmux prefix + O (rotate clockwise)

[[keyboard.bindings]]
key = "RBracket"
mods = "Command|Shift"
chars = "\u0002\u006f" # remote tmux prefix + o (rotate counter-clockwise)

[bell]
animation = "Linear"
duration = 1
color = "#ffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]
