[package_management]
manager = "uv"

[experimental]

[diagnostics]

[server]
follow_symlink = false
browser = "default"

[runtime]
auto_reload = "off"
on_cell_change = "autorun"
auto_instantiate = true
reactive_tests = true
output_max_bytes = 8000000
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000

[ai]
rules = ""

[ai.google]

[ai.anthropic]

[ai.open_ai]

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[snippets]
custom_paths = []
include_default_snippets = true

[keymap]
preset = "vim"
[keymap.overrides]

[display]
dataframes = "rich"
cell_output = "above"
default_table_page_size = 10
default_width = "medium"
theme = "light"
code_editor_font_size = 14

[language_servers.pylsp]
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_flake8 = false
enable_pyflakes = false
enable_mypy = true
enable_pylint = false

[completion]
copilot = "codeium"
activate_on_typing = true

[formatting]
line_length = 79
